name: video_edit_player
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
 
  cupertino_icons: ^1.0.2

  file_picker: ^5.5.0
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  url_launcher: ^6.1.14
  video_trimmer: ^2.1.0
  cloud_firestore: ^4.15.8
  dropdown_button2: ^2.3.9
  fluttertoast: ^8.2.5
  video_editor: ^3.0.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
