// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp-w2EoSwztv8kYLj6br_8ziWXPI7atrw',
    appId: '1:798973735070:web:bb1196cdc896fbdfde0b8f',
    messagingSenderId: '798973735070',
    projectId: 'newcodev-5c41f',
    authDomain: 'newcodev-5c41f.firebaseapp.com',
    databaseURL: 'https://newcodev-5c41f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newcodev-5c41f.appspot.com',
    measurementId: 'G-4XK27TQVXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfP0Jql3OEKPOgHi2fLm_HB0j5gieRo90',
    appId: '1:798973735070:android:ef4d08beafb35c3cde0b8f',
    messagingSenderId: '798973735070',
    projectId: 'newcodev-5c41f',
    databaseURL: 'https://newcodev-5c41f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newcodev-5c41f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVeY4G_JWKH2g2HB_sz5Us4_2PLFNwOnQ',
    appId: '1:798973735070:ios:c42a418e835f80e1de0b8f',
    messagingSenderId: '798973735070',
    projectId: 'newcodev-5c41f',
    databaseURL: 'https://newcodev-5c41f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'newcodev-5c41f.appspot.com',
    iosBundleId: 'com.example.videoEditPlayer',
  );
}
